spring:
  application:
    name: user-service

  config:
    import: configserver:http://localhost:9094

server:
  port: 9092




#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:9091/eureka
#  instance:
#    prefer-ip-address: true

# loadbalancer.ribbon.enabled: true  # Uncomment if needed
